theme: jekyll-theme-cayman
title: Regional Attention Network (RAN) for Head Pose and Fine-grained Gesture Recognition
description: IEEE Transactions on Affective Computing 2020
github:
  is_project_page: false
